version: '3.1'

services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nwclib
    ports:
      - 127.0.0.1:5432:5432