### Create web component
POST http://localhost:8080/webcomponents
Content-Type: application/json

{
  "name": "Button1",
  "description": "A simple button",
  "script": "script",
  "image": "image"
}

### Get web components
GET http://localhost:8080/webcomponents?pageNumber=0&pageSize=3